steps:
- name: gcr.io/kaniko-project/executor:latest
  args: ['--destination=gcr.io/$PROJECT_ID/built-with-kaniko-demo',
         '--cache=true']
tags: ['cloud-builders-community']
options:
  anthosCluster:
    membership: projects/793665742643/locations/global/memberships/tr3
